name: women_safety_final_project
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2 
  google_fonts: ^4.0.3
  carousel_slider: ^4.2.1
  webview_flutter: ^4.0.2
  flutter_phone_direct_caller: ^2.1.1
  url_launcher: ^6.1.9
  fluttertoast: ^8.2.1
  lottie: ^2.2.0
  firebase_core: ^2.6.1
  firebase_auth: ^4.2.8
  firebase_analytics: ^10.1.3
  cloud_firestore: ^4.4.2
  shared_preferences: ^2.0.17
  permission_handler: ^10.2.0
  contacts_service: ^0.6.3
  provider: ^6.0.5
  sqflite: ^2.2.4+1
  background_sms: ^0.0.4
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  image_picker: ^0.8.6+3
  uuid: ^3.0.7
  firebase_storage: ^11.0.14
  cached_network_image: ^3.2.3
  shake: ^2.2.0


  flutter_spinkit: ^5.1.0
  pinput: ^1.2.1
  flutter_slidable: ^0.6.0
  location: ^2.3.5
  sms_maintained: ^0.2.5
    
  # telephony: ^0.2.0
  # vibration: ^1.7.6
  # flutter_background_service: ^2.4.6
  flutter_background_service: ^0.1.5
  workmanager: ^0.5.1
  
      
dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/

  